server:
  port: 8085

spring:
  application:
    name: NotificationService
  cloud:
    consul:
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        instance-id: ${spring.application.name}:${random.value}
        service-name: notification-service
      host: localhost
      port: 8500
    openfeign:
      client:
        config:
          default:
            loggerLevel: FULL
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: com.pfa.eventservice.entities.Event:com.pfa.notificationservice.dtos.Event
    topic:
      name: events-topic

  mail:
    host: "smtp.gmail.com"
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}